# Generated by Django 6.0.5 on 2026-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('railway', 'Railway'), ('football', 'Football'), ('community', 'Community')], default='friend', max_length=30)),
                ('tribute_text', models.TextField()),
                ('light_candle', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
