# Generated by Django 6.0.5 on 2026-06-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialpost',
            name='relationship',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('railway', 'Railway'), ('football', 'Football'), ('community', 'Community'), ('other', 'Other')], default='friend', max_length=30),
        ),
    ]
